ucfopen/Materia-Server-Client-Assets

- src/js/controllers/ctrl-create.js
- src/js/controllers/ctrl-player.js
- src/js/controllers/ctrl-player.test.js
- src/js/materia/materia.creatorcore.js
- src/js/materia/materia.creatorcore.test.js
- src/js/materia/materia.enginecore.js
- src/js/materia/materia.enginecore.test.js
Standardized alert logic in creator-core, ctrl-create, engine-core, and ctrl-player, as well as their associated tests.
All alerts use the following parameters: `{msg, title = '', fatal = false}`. Creator alerts have an optional `enableLoginButton` parameter in the creator-core. The old creator alert parameters were: `{title, msg, type}`, meaning references to those within widgets will have to be updated.
> Fixes for creator and engine alerts

- src/js/controllers/ctrl-scores.js
> fixes score screen errors when linked from profile

- src/js/controllers/ctrl-player.js
- src/js/controllers/ctrl-player.test.js
- src/js/materia/materia.enginecore.js
- src/js/materia/materia.enginecore.test.js
Closes #21.
Added engine core and player controller methods to enable widgets to scroll to a vertical location.
> Allow widgets to scroll the page vertically.

- .travis.yml
- package.json
- yarn.lock
When travis runs trying to detect prettier changes - it failed in a cryptic way.  This adds an error output that should leave breadcrumbs for people.
* Convert lint-staged to always running prettier
* Pre-commit will no longer allow you to git add *some* files (it's checking for any un-added changes in src - you'll have to run `git commit --no-verify` to bypass)
* added `prettier:detectchanges` for clarity
> fix lint-staged, add more explicit prettier change detection

- src/js/controllers/ctrl-create.js
Closes #37.
Imported questions and all of their answers now have the 'id' properties set to null, allowing the backend to set them freshly to prevent collisions.
> Strip question and answer IDs from imported questions.

- src/css/scores.scss
Closes #31.
Closes #4.
Relies on https://github.com/ucfopen/Materia/pull/1184.
Modify styling rules to expect a table where the scores go instead of an unordered list that's hacked together to act like a table.
> Adjust score screen styling rules to act on tables instead of unordered lists pretending to be tables.

- src/js/controllers/ctrl-create.js
- src/js/controllers/ctrl-my-widgets.js
- src/js/controllers/ctrl-selectedwidget.js
- src/js/controllers/ctrl-selectedwidget.test.js
- src/js/services/srv-selectedwidget.js
- src/js/services/srv-widget.js
- src/js/services/srv-widget.test.js
Closes #48.
Relies on #47.
Detaches the act of locking a widget instance from clicking the 'Edit Widget' button in the My Widgets page and does it in the creator instead.
Only remaining (possible) issue: If a student tries getting clever and goes straight to the create URL of a widget instance, the checks will now prevent the creator from loading - but will still lock that instance.
Either need to consider retooling how the various methods work, or create a new endpoint that can unlock a widget instance.
> Adjust 'this person can edit this widget' checks on My Widgets page, locks widget instances in creator.

- src/js/services/srv-widget.js
- src/js/services/srv-widget.test.js
Slight change to the message displayed when somebody tries editing a locked widget.
> Minor tweak to 'widget is locked' message.

- src/js/controllers/ctrl-create.js
Fixes the creator controller's check to see if a user can edit a published widget.
Was breaking when creating a new widget since `is_draft` was undefined.
> Creator controller checkUserPublishPerms new widget fix.

- src/js/controllers/ctrl-export-scores.js
Fixes issue #1243 on Materia.
- Add check for when the semesters object is empty.
> #1243 TypeError: Cannot set property 'checked' of undefined when selecting export options on widget with no scores

- src/css/my-widgets.scss
- src/css/util-lti-picker.scss
- Remove CSS that is no longer used.
- Add CSS for the external link image
Fixes issue #1129 in Materia
Relies on Pull request #1234 in Materia
> #1129 lti picker doesn't handle long titles

- src/js/materia/materia.creatorcore.js
- src/js/materia/materia.creatorcore.test.js
- src/js/materia/materia.enginecore.js
- src/js/materia/materia.enginecore.test.js
For issue #78 
- Added check of e.data in a POST request before it is passed to JSON.parse
> #78 Materia.Engine does not check if received POST messages are valid

- src/css/widget-guide.scss
Recolored the frame for the helper docs page:
> CSS tweaks to helper docs frame

- src/js/controllers/ctrl-lti.js
- src/js/services/srv-widget.js
For [#1259](https://github.com/ucfopen/Materia/issues/1259) in the Materia repository.
- Add for update flag for when refresh is clicked in the lti list. Defaults to false so old functions should work the same
- Change get multiplefromserver to consistently update widgets in the list
> #1259 lti picker refresh fix

- src/js/materia/materia.scorecore.js
I fixed this in the engine and creator core but neglected to add it for score core. Just a small check to see if the data passed to JSON.parse is a string first.
See #78 for the original issue and #79 for the PR fixing it.
> #78 Add data type check for scorecore

- src/css/my-widgets.scss
- src/css/partials/_widget_availability_modal.scss
- src/css/partials/_widget_copy_modal.scss
- src/css/partials/_widget_share_modal.scss
- src/js/controllers/ctrl-selectedwidget.js
- src/js/controllers/ctrl-widget-settings.js
- src/js/services/srv-widget.js
To be paired with https://github.com/ucfopen/Materia/pull/1290
Additional notes and screenshots are on that pull request
- Added "retain ownership" checkbox to copy modal with clarifying wording
- Added clarifying information at the top of the Settings modal when viewed as a student
- Fixed wonky and unintuitive behavior with access level toggles
- Improved visibility and clarity of disabled access level toggles when a widget is student-made
- Ensured student access removal alert will display regardless of which access toggles are selected or deselected
Some changes still WIP
> Widget Copy modal & Settings updates to better clarify permissions

- src/css/scores.scss
It was difficult but I persevered and managed to come out with the "W"
#80
> issue/80 - decrease margin-top of embedded score page

- src/css/partials/_lti_embed_preview.scss
- src/css/util-lti-picker.scss
- src/js/controllers/ctrl-lti-resource-selection.js
- src/js/controllers/ctrl-score-page.js
- src/js/controllers/ctrl-widget-player.js
- src/js/controllers/ctrl-widget-player.test.js
- src/js/directives/dir-scoretable.js
- src/js/directives/dir-scoretable.test.js
* updates styles of embedded lti preview page
* requires materia server changes on https://github.com/ucfopen/Materia/pull/1300
* removes support for older `/scores/:inst_id/#single-:play_id` urls, migrated to `scores/single/:play_id/:inst_id`
> enable previewing and embed together

- src/js/controllers/ctrl-lti-resource-selection.js
Allows lti resource selection return url to handle query params given by the LMS.
Previously, If the picker was launched with with a `launch_presentation_return_url` that contained query params, materia incorrectly assumed there were none and simply appended a `?var=value` to the return url.
Now, the code will detect if it needs to append a question mark or an ampersand.
> lti picker handles query params in return url

- src/css/core.scss
- src/css/partials/_lti_embed_preview.scss
- src/css/partials/_widget_share_modal.scss
- src/js/controllers/ctrl-my-widgets-collaboration.js
- src/js/controllers/ctrl-my-widgets-selected.js
- src/js/controllers/ctrl-my-widgets.js
- src/js/controllers/ctrl-user-notification.js
Adds a new option to the LTI embed preview screen that's circumstantially enabled if a user is not an owner of the widget. It allows a user to request access to the embedded widget. The selected owner will be given a notification with an option to grant ownership to the person who made the request.
To be paired with https://github.com/ucfopen/Materia/pull/1344
> Access Request option for LTI previews

- src/js/controllers/ctrl-score-page.js
Closes #124.
Adds 'score_url' to the JSON payload of the 'materiaScoreRecorded' post message sent by the score screen.
> Add URL of score screen to score screen's post message.

- src/js/services/srv-widget.js
- src/js/services/srv-widget.test.js
Adds a call to a new API endpoint that confirms a user has the permissions necessary to see a widget in the My Widgets page.
> Prevent users from seeing widgets in My Widgets that they don't have access to.
